version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
      exclude-functions:
        - (*database/sql.Tx).Rollback
        - (*os/exec.Cmd).Wait
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
      - linters:
          - errcheck
        text: "Error return value of .*(Rollback|Close|Wait|Scan).*is not checked"

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - sb-proxy

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
