run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
  disable:
    - typecheck

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
    exclude-functions:
      - (*database/sql.Tx).Rollback
      - (*os/exec.Cmd).Wait
  gofmt:
    simplify: true
  goimports:
    local-prefixes: sb-proxy

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - linters:
        - errcheck
      text: "Error return value of .*(Rollback|Close|Wait|Scan).*is not checked"
  max-issues-per-linter: 50
  max-same-issues: 10
